# General Jekyll Config
pygments: true
url: http://leonidmirsky.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#18BCEB'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: leonidlm
    twitter: leonidlm
    linkedin: leonidmirsky
    email: leonidlm@gmail.com

  # "Hi, I'm _______"
  name: Leonid Mirsky
  email: leonidlm@gmail.com

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-44700272-1
  google_analytics_sitename: leonidmirsky.com

